version: '3.4'
services:
  bot:
    image: themasteredpanda/tldr-bot:latest
    container_name: tldr-bot
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - "./.env:/TLDR-Bot/.env"
      - "./service_account.json:/TLDR-Bot/service_account.json"

  api:
    image: hattyot/tldr-api:latest
    container_name: tldr-api
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "443:443"
    volumes:
      - "./.env:/TLDR-Api/.env"
      - "/etc/letsencrypt/:/etc/letsencrypt/"

networks:
  default:
    external:
      name: tldr-net
