version: '3.4'
services:
  bot:
    image: hattyot/tldr-bot:latest
    container_name: tldr-bot
    build:
      context: .
      dockerfile: Dockerfile-bot
    env_file:
      - ./.env

  api:
    image: hattyot/tldr-api:latest
    container_name: tldr-api
    build:
      context: .
      dockerfile: Dockerfile-api
    env_file:
      - ./.env
    ports:
      - "443:443"
