version: '3'
services:
  db:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    restart: always
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python3.8 bot.py"
    depends_on:
      - db
    links:
      - db
    environment:
      MAGICK_HOME: /usr

volumes:
  mongodb_data_container: