- name: clone or update tldrbot repo
  git:
    repo: "{{ tldrbot_repo }}"
    dest: /home/tldrbot/TLDR-Bot
    version: master
    force: yes

- name: copy db config
  copy:
    src: env_file_encrypted
    dest: /home/tldrbot/TLDR-Bot/.env

- name: deploy mongodb docker container
  docker_compose:
    project_src: /home/tldrbot/TLDR-Bot
    files: docker-compose-deploy-database.yml
    pull: yes

- name: copy over backup and restore scripts
  template:
    src: "{{ item }}"
    dest: "/home/tldrbot/mongodb/{{ item }}"
    mode: "+x"
  with_items:
    - backup.sh
    - restore.sh

- name: set up cron task for database backup
  cron:
    name: "mongodb"
    minute: "0"
    hour: "2"
    job: "/home/tldrbot/mongodb/backup.sh >/dev/null 2>&1"