- name: clone or update tldrbot repo
  git:
    repo: "{{ tldrbot_repo }}"
    dest: /home/tldrbot/TLDR-Bot
    version: master

- name: copy db config
  copy:
    src: env_file_encrypted
    dest: /home/tldrbot/TLDR-Bot/.env

- name: deploy mongodb docker container
  docker_compose:
    project_src: /home/tldrbot/TLDR-Bot
    files: docker-compose-deploy-database.yml
    pull: yes